- name: Install helm
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
          - name: download helm
            shell: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -

          - name: giving exe permission
            shell: sudo apt-get install apt-transport-https --yes

          - name: echo
            shell: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

          - name: update
            shell: sudo apt-get update

          - name: install helm
            apt-get:
                    name: helm
                    state: present
