---
- name: Install Jenkins
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
          - name: install openjdk
            apt:
                    name: default-jre
                    state: present
          - name: download jenkins.repo
            shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

          - name: import jenkins key
            shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

          - name: Update
            shell: sudo apt update

          - name: install jenkins
            apt:
                    name: jenkins
                    state: present
          - name: start jenkins
            shell: sudo systemctl start jenkins

          - name: sleep for 30 seconds and continue with play
            wait_for: timeout=30
            delegate_to: localhost
          - name: init password jenkin
            shell: cat /var/lib/jenkins/secrets/initialAdminPassword
            changed_when: false
            register: result
          - name: print password jenkins
            debug:
                    var: result.stdout
