apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
    labels:
      app: myapp
      type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx



------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
      name: webapp-green
spec:
  containers:
  - name: simple-webapp
    image: kodekloud/webapp-color
    args: ["--color", "green"]


-------------------------------


apiVersion: v1
kind: Pod
metadata:
    name: webapp-color
    labels:
      name: webapp-color
    namespace: default
spec:
  containers:
    - env:
        - name: APP_COLOR
          value: green
      image: kodekloud/webapp-color
      name: webapp-color

---------------------------------

apiVersion: v1
kind: Pod
metadata:
    name: webapp-color
    labels:
      name: webapp-color
    namespace: default
spec:
  containers:
    - envFrom:
        - configMapRef:
                name: webapp-config-map
      image: kodekloud/webapp-color
      name: webapp-color

------------------------------------

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret